name: Build SwitchPixelGameEngine

on: [push]
jobs:
  SwitchPixelGameEngine:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
    
    - name: 🧰 Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    # - uses: actions/checkout@v1
    # - name: Update repo.
    #   run: |
    #    git submodule update --init --recursive
        
    - name: Building SwitchPixelGameEngine
      run: |
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: SwitchPixelGameEngine
        path: SwitchPixelGameEngine.nro
